START = "START"
MENU_PRINCIPAL = "MENU_PRINCIPAL"

DESARROLLO_TIPO = "DESARROLLO_TIPO"
DESARROLLO_IDEA = "DESARROLLO_IDEA"
DESARROLLO_ARCHIVO = "DESARROLLO_ARCHIVO"
DESARROLLO_DESCRIPCION = "DESARROLLO_DESCRIPCION"
DESARROLLO_CONFIRMACION = "DESARROLLO_CONFIRMACION"

EMAIL_PREGUNTA = "EMAIL_PREGUNTA"
EMAIL_INGRESO = "EMAIL_INGRESO"

ASESORAMIENTO = "ASESORAMIENTO"
ASESORAMIENTO_IDEA = "ASESORAMIENTO_IDEA"
ASESORAMIENTO_CONFIRMACION = "ASESORAMIENTO_CONFIRMACION"

CONTACTO_HUMANO = "CONTACTO_HUMANO" 
CONTACTO_CONFIRMACION = "CONTACTO_CONFIRMACION"

FAQ_MENU = "FAQ_MENU"

CIERRE = "CIERRE"
FIN = "FIN"
