# Generated by Django 4.2 on 2026-01-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_nodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('interesado', 'Interesado'), ('calificado', 'Calificado'), ('agenda', 'Agendó reunión'), ('descartado', 'Descartado')], default='nuevo', max_length=20),
        ),
    ]
